### ISSUE TITLE
Frame_2D_GUI (_Metric)

### ISSUE THREAD

**Issue by Lomarandil** [buddyd16/Structural-Engineering#14]
I know it's in alpha, but I pulled down the Frame program to do some quick back-of-envelope checks a few weeks ago. When I did, I noticed that successively clicking the "solve" button changes the solution. It appears that the load effects are getting incremented each time. 

Thanks!

**Comment by buddyd16** [comment]
Good catch, assume you have the columns set as compressible? The member results don't get cleared on successive clicks of the solve button, so if the columns are compressible it would keep changing the results slightly until things converge, this is due to the program only performing the shortening action once. If columns aren't set as compressible it should solve in a single pass and give back the same results, at least in theory I'll run some checks to see what's happening.

**Comment by Lomarandil** [comment]
I was running the model using compressible columns, although my gut feel
from the results I was seeing was that the increment was larger than the
differential shortening alone

Please excuse brevity, sent from mobile

**Comment by buddyd16** [comment]
yep your right it's double the results each time you hit solve, I'll get it sorted.

**Comment by buddyd16** [comment]
just uploaded a fix, whenever you have some time if you could re-run it with your parameters and let me know if it's sorted on your end also that would be great. 
Thanks for reporting this!

**Comment by Lomarandil** [comment]
A quick look appears that this has been solved. Thanks!
